[tools]
node = "24"
deno = "2.6"
ruby = "3.4"
kubectl = "1.33"
kustomize = "5.8"
helm = "3.19"
argocd = "3.2"
argo-rollouts = "1.8"
"npm:pnpm" = "latest"
"npm:prettier" = "latest"
"npm:aws-cdk" = "latest"
"npm:firebase-tools" = "latest"
"npm:serverless" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:ccusage" = "latest"
"npm:@marp-team/marp-cli" = "latest"
"pipx:ansible-core" = "latest"

[settings]
experimental = true

[settings.pipx]
uvx = true
